### ISSUE TITLE
Missing Spanish in the bat script

### ISSUE THREAD

**Issue by sanguino** [supermarsx/magickeyboard#2]
Hi, 

There is no Spanish part in the install_keyboard_layouts.bat, but the SpanishA.dll exists. I tried to change the file, but there are three ids that I dont know where to find it. Can you help me?

I anyone have the ids I can make the PR.

Thanks!

**Comment by sanguino** [comment]
I just found it:

``` 
REM Spanish Layout
reg add "HKLM\SYSTEM\CurrentControlSet\Control\Keyboard Layouts\a000040a" /v "Layout Text" /t REG_SZ /d "Spanish (Apple)" /f >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Control\Keyboard Layouts\a000040a" /v "Layout File" /t REG_SZ /d "SpanishA.dll" /f >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Control\Keyboard Layouts\a000040a" /v "Layout Id" /t REG_SZ /d "00c5" /f >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Control\Keyboard Layouts\a000040a" /v "Layout Component ID" /t REG_SZ /d "C3364C7C44BC444A88A50459135D35B5" /f >nul 2>&1
```

do you need me to do a PR ?

Thanks

**Comment by supermarsx** [comment]
Hi, 

i appreciate you opening this issue and adding something so important! I've added to both install and uninstall scripts after confirming with a `bootcamp.xml` i had around. I don't require a PR though, it's ok by me :) 
I'm closing since it's solved.

commits: 84c687845d0436bcd80d62ee1fbffb10306ebe07 1bbe8230f35f819b3ce6a29394adc980e4b85bb5

Thank you!
